PLAYBACK = "playback"
PLAYBACK_STOPPED = PLAYBACK + ' stopped'

SELECT = "select"
FILE = "file"
FILES = FILE + "s"
FORMAT = "format"
FORMATS = FORMAT+'s'
PLAYLIST = "playlist"
ALL_FILES = "all " + FILES
SOUND_FILES = "sound " + FILES
SELECT_SOUND_FILES = SELECT + " " + SOUND_FILES
SELECT_PLAYLIST = SELECT + " " + PLAYLIST
PLAYLIST_FILE = PLAYLIST + " " + FILE
PLAYLIST_FORMATS = PLAYLIST + " " + FORMATS
OUTPUT_FOLDER = "output folder"
SELECT_OUTPUT_FOLDER = SELECT + ' ' + OUTPUT_FOLDER

LOAD = "load"
SAVE = "save"

LOAD_PLAYLIST = LOAD + ' ' + PLAYLIST
SAVE_PLAYLIST = SAVE + ' ' + PLAYLIST

INDEXER = "Indexer"
CUE_INDEXER = 'CUE ' + INDEXER
FILE_INDEXER = "File " + INDEXER

ERROR_AT_LINE_NEWLINE = 'Error at line:\n'
INVALID_FILENAME_NEWLINE = 'invalid filename:\n'

DISPLAY_PROPERTIES = "Display Properties"


